### ISSUE TITLE
Leak of env vars

### ISSUE THREAD

**Issue by Foohx** [philibea/scaleway-containers-deploy#14]
Hi,

First of all, thank you for your work.

I just noticed that at the end of a deployment, all the environment variables present on Scaleway are leaked in the Github Action logs. Is it possible to hide this? 

My conf :
```yml
      - name: StepName
        id: deploy
        uses: philibea/scaleway-containers-deploy@v1.0.7
        with:
          type: deploy
          scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
          scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
          scw_containers_namespace_id: ${{ secrets.SCW_CONTAINERS_NAMESPACE_ID }}
          scw_registry: rg.fr-par.scw.cloud/xxxx/yyyy:staging
          scw_container_port: 3333
```

Example of leak in action logs :
```
waiting for namespace to be ready
Container Name:  staging
Container already exists and will be updated &{xxxx staging *** ready map[APP_KEY:xxxxCACHE_VIEWS:false DB_CONNECTION:mysql DRIVE_DISK:s3 HASH_DRIVER:bcrypt HOST:0.0.0.0 ....
```
